### PR TITLE
delete mnist/dpsgd directory

### PR DESCRIPTION
**Pull request by kraritt**

### CODE REVIEW

**Comment by Abir-Tx** [comment]
@karitkar7 So we are deciding to **drop** the _dpsgd_ permanently?

**Review by Abir-Tx — COMMENTED** [review]
If yes, then let me clear the documentation for the DPSGD too

**Review by Abir-Tx — APPROVED** [review]
Okay, dropping the **DPSGD**

**Comment by kraritt** [comment]
@Abir-Tx  Alright. As we don't ever need this.

**Pull request merged**
