### PR TITLE
Delete system/flcore/clients/clientbase.py

### PR DESCRIPTION
**Pull request by kraritt**
base further not needed

### CODE REVIEW

**Review by Abir-Tx — COMMENTED** [review]
Producing - ModuleNotFoundError: No module named 'flcore.clients.clientbase' error

**Comment by Abir-Tx** [comment]
This file is needed for `main.py` to run. Hence closing the PR. Sorry for this @karit7

**Comment by kraritt** [comment]
yeap, sorted out. sorry for the inconvenience.

**Comment by Abir-Tx** [comment]
> sorry for the inconvenience.

Mention not man

**Pull request closed without merging**
